### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by DanielRX** [loomnetwork/loom-truffle-provider#3]
Currently the typings in the NPM package are null, preventing type safety when using this with typescript.
Given the fact this is made in typescript, is this intentional?

**Comment by eduardonunesp** [comment]
Well I didn't work on typings although the project is on Typescript it intended to be used with Truffle which is JS framework, so the TS generates the JS lib before publishing on NPM

**Comment by DanielRX** [comment]
Truffle supports typescript test files in the latest versions, so this issue still remains. There is a usecase for typescript usage of this package that is not possible (or at least, not typesafe) purely because the types are exported. If the package is written in TS, it should be easy to add those types the npm package.

**Comment by eduardonunesp** [comment]
So fixing my previous statement, I was checking and the `d.ts` files are generated indeed, they exist on `node_modules/loom-js/dist/*.d.ts`, right now I'm using the VSCode and when I code in pure JS the editor autocomplete with all information about the types from `loom-js`, because the types exist on the package there's no needing from another package like `@types/loom-js`
